Repository trustbloc/vcs, pull requests merged in 2021-03, with the labels that each got.

#643 refactor: Vault BDD - removes sleep
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#645 chore: update aries revision
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  cmd/vc-rest/startcmd/start.go
  cmd/vc-rest/startcmd/start_test.go
  go.mod
  go.sum
  pkg/restapi/issuer/operation/operations_test.go
  test/bdd/fixtures/hub-kms/.env
  test/bdd/fixtures/vault-server/.env
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#646 chore: confidential-storage-hub, comparator
  cmd/comparator-rest/docs/openapi.yaml
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/docs/openapi.yaml
  cmd/confidential-storage-hub/go.sum
  cmd/did-rest/go.sum
  cmd/vault-server/go.sum
  pkg/client/comparator/models/authorized_query.go
  pkg/client/comparator/models/doc_query.go
  pkg/client/comparator/models/extract.go
  pkg/client/comparator/models/extract_resp.go
  pkg/client/comparator/models/query.go
  pkg/client/comparator/models/scope.go
  pkg/client/csh/client/operations/post_extract_responses.go
  pkg/client/csh/models/extraction_response.go
  pkg/restapi/comparator/operation/extract.go
  pkg/restapi/comparator/operation/models/authorized_query.go
  pkg/restapi/comparator/operation/models/doc_query.go
  pkg/restapi/comparator/operation/models/extract.go
  pkg/restapi/comparator/operation/models/extract_resp.go
  pkg/restapi/comparator/operation/models/query.go
  pkg/restapi/comparator/operation/models/scope.go
  pkg/restapi/comparator/operation/operations_test.go
  pkg/restapi/csh/operation/openapi.go
  pkg/restapi/csh/operation/openapi/extraction_response.go
  pkg/restapi/csh/operation/operations.go
  pkg/restapi/csh/operation/operations_test.go
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/chs/chs_steps.go
  test/bdd/pkg/chs/user.go
  test/bdd/pkg/comparator/comparator_steps.go
Labels: chore, cla-signed, comparator, confidential-storage-hub

#647 feat: add deriveCredential for holder
  pkg/restapi/holder/controller_test.go
  pkg/restapi/holder/operation/models.go
  pkg/restapi/holder/operation/openapi.go
  pkg/restapi/holder/operation/operations.go
  pkg/restapi/holder/operation/operations_test.go
Labels: cla-signed

#648 refactor: update status endpoint to match vc-http api
  pkg/doc/vc/status/csl/csl.go
  pkg/doc/vc/status/csl/csl_test.go
  pkg/internal/mock/edv/client.go
  pkg/restapi/issuer/operation/models.go
  pkg/restapi/issuer/operation/openapi.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  test/bdd/pkg/vc/vc_steps.go
Labels: cla-signed

#649 feat: Switch edge-core storage to Aries storage
  cmd/common/storage.go
  cmd/common/storage_test.go
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/confidential-storage-hub/startcmd/start.go
  cmd/confidential-storage-hub/startcmd/start_test.go
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  go.mod
  go.sum
  pkg/doc/vc/status/csl/csl_test.go
  pkg/internal/mock/storage/store.go
  pkg/restapi/csh/controller_test.go
  pkg/restapi/csh/operation/compare.go
  pkg/restapi/csh/operation/compare_test.go
  pkg/restapi/csh/operation/operations.go
  pkg/restapi/csh/operation/operations_test.go
  pkg/restapi/csh/operation/query_test.go
  test/bdd/go.mod
Labels: cla-signed

#650 chore: update trustbloc-did-method revision
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/comparator-rest/startcmd/start.go
  cmd/confidential-storage-hub/go.sum
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vault-server/startcmd/start.go
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  cmd/vc-rest/startcmd/start.go
  go.mod
  go.sum
  test/bdd/fixtures/did-method-rest/.env
  test/bdd/fixtures/sidetree-mock/.env
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/context/context.go
  test/bdd/pkg/issuer/issuer_steps.go
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#651 test: BDD test for comparator extraction of multiple documents
  test/bdd/features/comparator_e2e_api.feature
  test/bdd/go.sum
  test/bdd/pkg/comparator/comparator_steps.go
Labels: cla-signed, comparator, test

#653 feat: generate key pair to support custom keytypes
  pkg/restapi/issuer/operation/models.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
Labels: cla-signed

#652 chore: update latest dependencies
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  go.mod
  go.sum
  pkg/restapi/vault/client.go
  test/bdd/fixtures/did-method-rest/.env
  test/bdd/fixtures/hub-kms/.env
  test/bdd/fixtures/sidetree-mock/.env
  test/bdd/fixtures/stakeholder-server/config-data/stakeholder.one:8088.json
  test/bdd/fixtures/vault-server/.env
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#654 chore: update to latest AFG
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  go.mod
  go.sum
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#655 chore: Updates EDV image
  go.mod
  go.sum
  test/bdd/fixtures/edv-rest/.env
Labels: cla-signed

#657 feat: confidential-storage-hub - use did:trustbloc for identity
  Makefile
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/confidential-storage-hub/startcmd/start.go
  cmd/confidential-storage-hub/startcmd/start_test.go
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  go.mod
  go.sum
  pkg/did/creator.go
  pkg/did/creator_test.go
  pkg/did/helper.go
  pkg/did/helper_test.go
  pkg/key/creator.go
  pkg/key/creator_test.go
  pkg/restapi/csh/controller_test.go
  pkg/restapi/csh/operation/compare_test.go
  pkg/restapi/csh/operation/entity.go
  pkg/restapi/csh/operation/operations.go
  pkg/restapi/csh/operation/operations_test.go
  pkg/restapi/csh/operation/query.go
  pkg/restapi/csh/operation/query_test.go
  pkg/restapi/csh/operation/zcapld/zcapld.go
  pkg/restapi/vault/client.go
  pkg/restapi/vault/client_test.go
  test/bdd/fixtures/confidential-storage-hub/docker-compose.yml
  test/bdd/fixtures/hub-kms/docker-compose.yml
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/chs/chs_steps.go
  test/bdd/pkg/chs/user.go
  test/bdd/pkg/comparator/comparator_steps.go
Labels: cla-signed, confidential-storage-hub, enhancement

#659 feat: support for profiles with BBS signature type
  pkg/doc/vc/crypto/crypto.go
  pkg/doc/vc/crypto/crypto_test.go
  pkg/restapi/internal/common/did/common.go
  pkg/restapi/internal/common/did/common_test.go
  pkg/restapi/internal/common/vcutil/vcutil.go
  pkg/restapi/internal/common/vcutil/vcutil_test.go
Labels: cla-signed

#660 chore: Update aries-framework-go-ext storage commit versions
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#661 docs: add docs for CSH, Comparator, Vault Server
  README.md
  cmd/comparator-rest/README.md
  cmd/confidential-storage-hub/README.md
  cmd/vault-server/README.md
Labels: cla-signed, documentation

#662 chore: release 0.1.6
  ci/version_var.sh
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  go.mod
  go.sum
  test/bdd/fixtures/did-method-rest/.env
  test/bdd/fixtures/edv-rest/.env
  test/bdd/fixtures/hub-kms/.env
  test/bdd/fixtures/sidetree-mock/.env
  test/bdd/fixtures/vault-server/.env
  test/bdd/go.mod
  test/bdd/go.sum
Labels: chore, cla-signed

#663 chore: bump to 0.1.7
  ci/version_var.sh
Labels: chore, cla-signed

#664 feat: handle nonce cases
  pkg/restapi/holder/operation/models.go
  pkg/restapi/holder/operation/operations.go
  pkg/restapi/holder/operation/operations_test.go
Labels: cla-signed

#665 chore: change issuer and verifier endpoint path
  docs/vc-rest/api_overview.md
  docs/vc-rest/vc_interop_api_impl_status.md
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/verifier/operation/operations.go
  pkg/restapi/verifier/operation/operations_test.go
  test/bdd/pkg/issuer/issuer_steps.go
  test/bdd/pkg/vc/vc_steps.go
  test/bdd/pkg/verifier/verifier_steps.go
Labels: cla-signed

#667 chore: update latest dependencies
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  go.mod
  go.sum
  test/bdd/fixtures/did-method-rest/.env
  test/bdd/fixtures/edv-rest/.env
  test/bdd/fixtures/hub-kms/.env
  test/bdd/fixtures/vault-server/.env
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#668 feat: add CredentialStatus to IssueCredentialOptions
  pkg/restapi/issuer/operation/models.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
Labels: cla-signed

#669 chore: use did:web aries
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  pkg/restapi/did/operation/operations.go
  pkg/restapi/did/operation/operations_test.go
Labels: cla-signed

#671 fix: add vc status list for each profile
  pkg/doc/vc/status/csl/csl.go
  pkg/doc/vc/status/csl/csl_test.go
  pkg/restapi/governance/operation/operations.go
  pkg/restapi/governance/operation/operations_test.go
  pkg/restapi/issuer/operation/openapi.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/verifier/operation/operations.go
  pkg/restapi/verifier/operation/operations_test.go
Labels: cla-signed

#672 fix: add bbsBlsSignature2020Context for vc status list
  pkg/doc/vc/status/csl/csl.go
Labels: cla-signed

#673 chore: update trustbloc vdr
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/comparator-rest/startcmd/start.go
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/confidential-storage-hub/startcmd/start.go
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vault-server/startcmd/start.go
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  cmd/vc-rest/startcmd/start.go
  cmd/vc-rest/startcmd/start_test.go
  go.mod
  go.sum
  pkg/client/vault/reader_test.go
  pkg/did/creator_test.go
  pkg/internal/cryptosetup/cryptosetup.go
  pkg/internal/cryptosetup/cryptosetup_test.go
  pkg/restapi/csh/operation/query_test.go
  pkg/restapi/csh/operation/zcapld/zcapld_test.go
  pkg/restapi/vault/client.go
  test/bdd/fixtures/did-method-rest/.env
  test/bdd/fixtures/hub-kms/.env
  test/bdd/fixtures/vault-server/.env
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/chs/user.go
  test/bdd/pkg/context/context.go
  test/bdd/pkg/issuer/issuer_steps.go
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#674 chore: update to aries 7ec3a2c4697c512726ffaa4143e56491405dd828
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  go.mod
  go.sum
  pkg/restapi/csh/operation/zcapld/dependencies.go
  pkg/restapi/csh/operation/zcapld/zcapld_test.go
  pkg/restapi/governance/operation/operations_test.go
  pkg/restapi/holder/operation/operations.go
  pkg/restapi/holder/operation/operations_test.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/verifier/operation/operations.go
  test/bdd/fixtures/did-method-rest/.env
  test/bdd/fixtures/hub-kms/.env
  test/bdd/fixtures/vault-server/.env
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/bddutil/util.go
  test/bdd/pkg/vault/vault_steps.go
  test/bdd/pkg/vc/vc_steps.go
Labels: cla-signed
