Repository trustbloc/vcs, pull requests merged in 2021-02, with the labels that each got.

#575 chore: confidential-storage-hub skeleton
  Makefile
  ci/azure-pipelines.yml
  ci/version_var.sh
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/confidential-storage-hub/main.go
  cmd/confidential-storage-hub/main_test.go
  cmd/confidential-storage-hub/startcmd/start.go
  cmd/confidential-storage-hub/startcmd/start_test.go
  images/confidential-storage-hub/Dockerfile
  pkg/restapi/csh/controller.go
  pkg/restapi/csh/controller_test.go
  pkg/restapi/csh/operation/models.go
  pkg/restapi/csh/operation/openapi.go
  pkg/restapi/csh/operation/operations.go
  pkg/restapi/csh/operation/operations_test.go
  scripts/check_integration.sh
  scripts/check_lint.sh
  scripts/check_unit.sh
  scripts/generate-openapi-spec.sh
  test/bdd/bddtests_test.go
  test/bdd/features/confidential-storage-hub_e2e_api.feature
  test/bdd/fixtures/confidential-storage-hub/.env
  test/bdd/fixtures/confidential-storage-hub/docker-compose.yml
Labels: cla-signed

#573 feat: Creates new vault (API)
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vault-server/startcmd/start.go
  pkg/client/vault/client.go
  pkg/client/vault/client_test.go
  pkg/restapi/vault/controller.go
  pkg/restapi/vault/operation/openapi.go
  pkg/restapi/vault/operation/operations.go
  pkg/restapi/vault/operation/operations_test.go
Labels: cla-signed

#574 feat: Vault server BDD tests
  Makefile
  ci/azure-pipelines.yml
  ci/version_var.sh
  cmd/vault-server/go.mod
  cmd/vault-server/startcmd/start.go
  cmd/vault-server/startcmd/start_test.go
  images/vault-server/Dockerfile
  scripts/check_integration.sh
  scripts/check_lint.sh
  scripts/check_unit.sh
  scripts/generate_test_keys.sh
  test/bdd/bddtests_test.go
  test/bdd/features/vault_server_e2e_api.feature
  test/bdd/fixtures/vault-server/.env
  test/bdd/fixtures/vault-server/docker-compose.yml
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#580 chore: comment out failing interop test
  Makefile
  test/bdd/features/vc_e2e_api.feature
  test/bdd/features/verifier_e2e_api.feature
Labels: cla-signed

#581 docs: document vault-server
  README.md
  cmd/vault-server/README.md
  cmd/vault-server/docs/openapi.yaml
Labels: cla-signed, documentation, vault-server

#582 docs: comparator openapi specs and README
  README.md
  cmd/comparator-rest/README.md
  cmd/comparator-rest/docs/openapi.yaml
Labels: cla-signed, comparator, documentation

#579 feat: confidential-storage-hub /profiles
  cmd/common/storage.go
  cmd/common/storage_test.go
  cmd/comparator-rest/docs/openapi.yaml
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/README.md
  cmd/confidential-storage-hub/docs/openapi.yaml
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/confidential-storage-hub/startcmd/start.go
  cmd/confidential-storage-hub/startcmd/start_test.go
  cmd/did-rest/go.sum
  cmd/vault-server/docs/openapi.yaml
  cmd/vault-server/go.sum
  go.mod
  go.sum
  pkg/internal/mock/storage/store.go
  pkg/restapi/csh/controller_test.go
  pkg/restapi/csh/operation/middleware.go
  pkg/restapi/csh/operation/models.go
  pkg/restapi/csh/operation/operations.go
  pkg/restapi/csh/operation/operations_test.go
  test/bdd/bddtests_test.go
  test/bdd/features/confidential-storage-hub_e2e_api.feature
  test/bdd/fixtures/confidential-storage-hub/.env
  test/bdd/fixtures/confidential-storage-hub/docker-compose.yml
  test/bdd/go.sum
  test/bdd/pkg/chs/chs_steps.go
  test/bdd/pkg/chs/user.go
Labels: cla-signed, confidential-storage-hub, enhancement

#583 feat: setup comparator models
  Makefile
  go.mod
  go.sum
  pkg/restapi/comparator/controller_test.go
  pkg/restapi/comparator/operation/models.go
  pkg/restapi/comparator/operation/openapi.go
  pkg/restapi/comparator/operation/operations.go
  pkg/restapi/comparator/operation/operations_test.go
Labels: cla-signed

#584 feat: Saves documents into EDV
  ci/azure-pipelines.yml
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vault-server/startcmd/start.go
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  go.mod
  go.sum
  pkg/client/vault/client.go
  pkg/client/vault/client_test.go
  pkg/restapi/vault/operation/openapi.go
  pkg/restapi/vault/operation/operations.go
  pkg/restapi/vault/operation/operations_test.go
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#588 feat: create config at comparator startup
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/comparator-rest/startcmd/start.go
  cmd/comparator-rest/startcmd/start_test.go
  go.mod
  pkg/restapi/comparator/controller_test.go
  pkg/restapi/comparator/operation/models.go
  pkg/restapi/comparator/operation/openapi.go
  pkg/restapi/comparator/operation/operations.go
  pkg/restapi/comparator/operation/operations_test.go
  test/bdd/bddtests_test.go
  test/bdd/features/comparator_e2e_api.feature
  test/bdd/fixtures/comparator-rest/.env
  test/bdd/fixtures/comparator-rest/docker-compose.yml
  test/bdd/pkg/bddutil/util.go
  test/bdd/pkg/comparator/comparator_steps.go
Labels: cla-signed

#589 feat: Implements get documents metadata endpoint.
  pkg/client/vault/client.go
  pkg/client/vault/client_test.go
  pkg/restapi/vault/operation/openapi.go
  pkg/restapi/vault/operation/operations.go
  pkg/restapi/vault/operation/operations_test.go
Labels: cla-signed

#593 feat: Vault Server - Health check endpoint
  cmd/vault-server/startcmd/start.go
  pkg/restapi/healthcheck/controller.go
  pkg/restapi/healthcheck/operation/operations.go
  test/bdd/features/vault_server_e2e_api.feature
Labels: cla-signed

#594 test: Vault Server BDD tests
  test/bdd/features/vault_server_e2e_api.feature
  test/bdd/fixtures/vault-server/.env
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#591 feat: comparator: Register at Confidential Hub Storage at startup
  cmd/comparator-rest/go.sum
  cmd/comparator-rest/startcmd/start.go
  cmd/comparator-rest/startcmd/start_test.go
  pkg/client/csh/client.go
  pkg/client/csh/client_test.go
  pkg/restapi/comparator/operation/openapi.go
  pkg/restapi/comparator/operation/operations.go
  pkg/restapi/comparator/operation/operations_test.go
  scripts/generate_test_keys.sh
  test/bdd/bddtests_test.go
  test/bdd/fixtures/comparator-rest/docker-compose.yml
Labels: cla-signed

#595 feat: Vault server TLS support
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/go.sum
  cmd/did-rest/go.sum
  cmd/vault-server/go.sum
  cmd/vault-server/startcmd/start.go
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  go.mod
  go.sum
  pkg/client/vault/client.go
  test/bdd/features/vault_server_e2e_api.feature
  test/bdd/fixtures/vault-server/docker-compose.yml
  test/bdd/go.sum
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#596 fix: rename confidential-storage-hub to hub-confidential-storage
  ci/azure-pipelines.yml
Labels: cla-signed

#597 fix: hub-confidential-storage publish build
  Makefile
  ci/version_var.sh
  test/bdd/fixtures/confidential-storage-hub/.env
Labels: cla-signed

#598 fix: config keys for comparator
  pkg/restapi/comparator/operation/models.go
  pkg/restapi/comparator/operation/operations.go
Labels: cla-signed

#599 feat: Vault server - database support.
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vault-server/startcmd/start.go
  cmd/vault-server/startcmd/start_test.go
  test/bdd/fixtures/vault-server/.env
  test/bdd/fixtures/vault-server/docker-compose.yml
Labels: cla-signed

#600 fix: Vault server - generates id when it is empty.
  pkg/client/vault/client.go
  pkg/client/vault/client_test.go
  pkg/restapi/vault/operation/operations.go
  pkg/restapi/vault/operation/operations_test.go
  test/bdd/features/vault_server_e2e_api.feature
  test/bdd/fixtures/vault-server/docker-compose.yml
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#601 feat: Vault server - adds authorizations
  ci/azure-pipelines.yml
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  go.mod
  go.sum
  pkg/client/vault/client.go
  pkg/client/vault/client_test.go
  pkg/restapi/vault/operation/openapi.go
  pkg/restapi/vault/operation/operations.go
  pkg/restapi/vault/operation/operations_test.go
  test/bdd/features/vault_server_e2e_api.feature
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#602 chore: configure vault url in comparator server
  cmd/comparator-rest/go.sum
  cmd/comparator-rest/startcmd/start.go
  cmd/comparator-rest/startcmd/start_test.go
  cmd/vault-server/startcmd/start.go
  pkg/client/vault/client.go
  pkg/client/vault/client_test.go
  pkg/restapi/comparator/operation/models.go
  pkg/restapi/comparator/operation/operations.go
  pkg/restapi/comparator/operation/operations_test.go
  pkg/restapi/vault/client.go
  pkg/restapi/vault/client_test.go
  pkg/restapi/vault/operation/openapi.go
  pkg/restapi/vault/operation/operations.go
  pkg/restapi/vault/operation/operations_test.go
  test/bdd/fixtures/comparator-rest/docker-compose.yml
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#604 fix: Vault server - id is a did (not did URL)
  pkg/restapi/vault/client.go
  pkg/restapi/vault/client_test.go
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#605 feat: /compare utilities
  pkg/client/vault/reader.go
  pkg/client/vault/reader_test.go
  pkg/restapi/csh/operation/zcapld/dependencies.go
  pkg/restapi/csh/operation/zcapld/zcapld.go
  pkg/restapi/csh/operation/zcapld/zcapld_test.go
Labels: cla-signed, confidential-storage-hub, enhancement

#606 fix: Vault server - removes restriction for the EDV ID
  pkg/restapi/vault/client.go
  pkg/restapi/vault/client_test.go
Labels: cla-signed

#607 feat: confidential-storage-hub /compare
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/docs/openapi.yaml
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  go.mod
  go.sum
  pkg/client/csh/client.go
  pkg/client/csh/client_test.go
  pkg/restapi/comparator/operation/operations.go
  pkg/restapi/csh/operation/compare.go
  pkg/restapi/csh/operation/compare_test.go
  pkg/restapi/csh/operation/models.go
  pkg/restapi/csh/operation/openapi.go
  pkg/restapi/csh/operation/openapi/authorization.go
  pkg/restapi/csh/operation/openapi/caveat.go
  pkg/restapi/csh/operation/openapi/comparison.go
  pkg/restapi/csh/operation/openapi/comparison_request.go
  pkg/restapi/csh/operation/openapi/doc_query.go
  pkg/restapi/csh/operation/openapi/eq_op.go
  pkg/restapi/csh/operation/openapi/error.go
  pkg/restapi/csh/operation/openapi/expiry_caveat.go
  pkg/restapi/csh/operation/openapi/operator.go
  pkg/restapi/csh/operation/openapi/profile.go
  pkg/restapi/csh/operation/openapi/query.go
  pkg/restapi/csh/operation/openapi/ref_query.go
  pkg/restapi/csh/operation/openapi/upstream_authorization.go
  pkg/restapi/csh/operation/operations.go
  pkg/restapi/csh/operation/operations_test.go
  pkg/restapi/csh/operation/query.go
  pkg/restapi/csh/operation/query_test.go
  scripts/check_license.sh
  test/bdd/go.sum
  test/bdd/pkg/chs/chs_steps.go
  test/bdd/pkg/chs/user.go
Labels: cla-signed, confidential-storage-hub, enhancement

#608 feat: Vault server - get authorization.
  pkg/restapi/vault/client.go
  pkg/restapi/vault/client_test.go
  pkg/restapi/vault/operation/operations.go
  pkg/restapi/vault/operation/operations_test.go
  test/bdd/features/vault_server_e2e_api.feature
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#609 chore: latest aries-framework-go
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  go.mod
  go.sum
  test/bdd/fixtures/did-method-rest/.env
  test/bdd/fixtures/edv-rest/.env
  test/bdd/fixtures/vault-server/.env
  test/bdd/go.mod
  test/bdd/go.sum
Labels: chore, cla-signed

#611 feat: Vault server - adds client
  pkg/client/vault/client.go
  pkg/client/vault/client_test.go
  pkg/restapi/comparator/operation/operations.go
  pkg/restapi/vault/client.go
  pkg/restapi/vault/client_test.go
  pkg/restapi/vault/operation/openapi.go
  pkg/restapi/vault/operation/operations.go
  pkg/restapi/vault/operation/operations_test.go
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#615 feat: Vault server - adds caveat expiry support
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  go.mod
  go.sum
  pkg/client/vault/client.go
  pkg/client/vault/client_test.go
  pkg/restapi/vault/client.go
  pkg/restapi/vault/client_test.go
  pkg/restapi/vault/operation/openapi.go
  pkg/restapi/vault/operation/operations.go
  test/bdd/features/vault_server_e2e_api.feature
  test/bdd/fixtures/edv-rest/.env
  test/bdd/fixtures/vault-server/.env
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#617 fix: Vault server - builds proper URL
  pkg/restapi/vault/client.go
Labels: cla-signed

#618 feat: Vault server - adds encKeyURI to the response
  pkg/restapi/vault/client.go
  pkg/restapi/vault/client_test.go
Labels: cla-signed

#620 docs: openapi specs for vault-server and comparator
  cmd/comparator-rest/docs/openapi.yaml
  cmd/vault-server/docs/openapi.yaml
Labels: cla-signed, documentation

#619 fix: Vault server - fixes EDV URL
  pkg/restapi/vault/client.go
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#616 chore: integrate with csh compare endpoint
  cmd/comparator-rest/go.sum
  cmd/comparator-rest/startcmd/start_test.go
  pkg/client/csh/models/caveat.go
  pkg/client/csh/models/operator.go
  pkg/client/csh/models/query.go
  pkg/restapi/comparator/controller_test.go
  pkg/restapi/comparator/operation/compare.go
  pkg/restapi/comparator/operation/openapi/config.go
  pkg/restapi/comparator/operation/operations.go
  pkg/restapi/comparator/operation/operations_test.go
  test/bdd/features/comparator_e2e_api.feature
  test/bdd/go.mod
  test/bdd/pkg/comparator/comparator_steps.go
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#622 refactor: comparator + vault-server openapi specs
  cmd/comparator-rest/docs/openapi.yaml
  cmd/vault-server/docs/openapi.yaml
Labels: cla-signed, refactor

#624 chore: create make target to generate models and client using go-swagger
  Makefile
  cmd/comparator-rest/docs/openapi.yaml
  pkg/client/comparator/client.go
  pkg/client/comparator/client/comparator_client.go
  pkg/client/comparator/client/operations/get_config_parameters.go
  pkg/client/comparator/client/operations/get_config_responses.go
  pkg/client/comparator/client/operations/operations_client.go
  pkg/client/comparator/client/operations/post_authorizations_parameters.go
  pkg/client/comparator/client/operations/post_authorizations_responses.go
  pkg/client/comparator/client/operations/post_compare_parameters.go
  pkg/client/comparator/client/operations/post_compare_responses.go
  pkg/client/comparator/client/operations/post_extract_parameters.go
  pkg/client/comparator/client/operations/post_extract_responses.go
  pkg/client/comparator/client_test.go
  pkg/client/comparator/models/authorization.go
  pkg/client/comparator/models/authorized_query.go
  pkg/client/comparator/models/caveat.go
  pkg/client/comparator/models/comparison.go
  pkg/client/comparator/models/comparison_result.go
  pkg/client/comparator/models/config.go
  pkg/client/comparator/models/doc_query.go
  pkg/client/comparator/models/eq_op.go
  pkg/client/comparator/models/error.go
  pkg/client/comparator/models/expiry_caveat.go
  pkg/client/comparator/models/operator.go
  pkg/client/comparator/models/query.go
  pkg/client/comparator/models/scope.go
  pkg/client/csh/client.go
  pkg/client/csh/client_test.go
  pkg/restapi/comparator/operation/compare.go
  pkg/restapi/comparator/operation/models/authorization.go
  pkg/restapi/comparator/operation/models/authorized_query.go
  pkg/restapi/comparator/operation/models/caveat.go
  pkg/restapi/comparator/operation/models/comparison.go
  pkg/restapi/comparator/operation/models/comparison_result.go
  pkg/restapi/comparator/operation/models/config.go
  pkg/restapi/comparator/operation/models/doc_query.go
  pkg/restapi/comparator/operation/models/eq_op.go
  pkg/restapi/comparator/operation/models/error.go
  pkg/restapi/comparator/operation/models/expiry_caveat.go
  pkg/restapi/comparator/operation/models/operator.go
  pkg/restapi/comparator/operation/models/query.go
  pkg/restapi/comparator/operation/models/scope.go
  pkg/restapi/comparator/operation/openapi.go
  pkg/restapi/comparator/operation/operations.go
  pkg/restapi/comparator/operation/operations_test.go
  scripts/generate-models-client.sh
  test/bdd/pkg/comparator/comparator_steps.go
Labels: cla-signed

#625 test: add Authorization test for comparator
  pkg/restapi/comparator/operation/operations.go
  pkg/restapi/comparator/operation/operations_test.go
  test/bdd/features/comparator_e2e_api.feature
  test/bdd/pkg/comparator/comparator_steps.go
Labels: cla-signed

#623 feat: confidential-storage-hub - implement RefQuery
  cmd/confidential-storage-hub/docs/openapi.yaml
  cmd/confidential-storage-hub/startcmd/start.go
  pkg/restapi/csh/operation/compare.go
  pkg/restapi/csh/operation/compare_test.go
  pkg/restapi/csh/operation/entity.go
  pkg/restapi/csh/operation/operations.go
  pkg/restapi/csh/operation/operations_test.go
  pkg/restapi/csh/operation/query_test.go
  test/bdd/features/confidential-storage-hub_e2e_api.feature
  test/bdd/fixtures/confidential-storage-hub/docker-compose.yml
  test/bdd/pkg/chs/chs_steps.go
  test/bdd/pkg/chs/user.go
Labels: cla-signed, confidential-storage-hub, enhancement

#626 fix: comparator openapi - missing auth tokens
  cmd/comparator-rest/docs/openapi.yaml
Labels: bug, cla-signed, comparator

#627 fix: add Content-Type json for return error
  pkg/restapi/comparator/operation/operations.go
Labels: cla-signed

#629 chore: update aries-framework-go revision
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  go.mod
  go.sum
  pkg/doc/vc/status/csl/csl.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/verifier/operation/operations.go
  pkg/restapi/verifier/operation/operations_test.go
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/bddutil/util.go
  test/bdd/pkg/issuer/issuer_steps.go
  test/bdd/pkg/vc/vc_steps.go
Labels: cla-signed

#630 feat: confidential-storage-hub - support JSONPath
  go.mod
  pkg/restapi/csh/operation/compare.go
  pkg/restapi/csh/operation/compare_test.go
  test/bdd/pkg/chs/chs_steps.go
  test/bdd/pkg/chs/user.go
Labels: cla-signed, confidential-storage-hub, enhancement

#631 fix: confidential-storage-hub - make profile.ID a URN
  pkg/restapi/csh/operation/operations.go
  pkg/restapi/csh/operation/operations_test.go
Labels: bug, cla-signed, confidential-storage-hub

#628 feat: implement comparator Authorization
  pkg/client/comparator/models/authorization.go
  pkg/client/comparator/models/scope.go
  pkg/restapi/comparator/controller_test.go
  pkg/restapi/comparator/operation/authz.go
  pkg/restapi/comparator/operation/models/authorization.go
  pkg/restapi/comparator/operation/models/scope.go
  pkg/restapi/comparator/operation/operations.go
  pkg/restapi/comparator/operation/operations_test.go
  scripts/check_license.sh
  test/bdd/features/comparator_e2e_api.feature
  test/bdd/pkg/comparator/comparator_steps.go
Labels: cla-signed

#632 feat: support AuthorizedQuery for comparator
  pkg/restapi/comparator/operation/compare.go
  pkg/restapi/comparator/operation/operations_test.go
  test/bdd/features/comparator_e2e_api.feature
  test/bdd/pkg/comparator/comparator_steps.go
Labels: cla-signed

#633 feat: Zcap - trustbloc did support
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  go.mod
  go.sum
  pkg/restapi/vault/client.go
  pkg/restapi/vault/client_test.go
  test/bdd/features/vault_server_e2e_api.feature
  test/bdd/fixtures/edv-rest/.env
  test/bdd/fixtures/edv-rest/docker-compose.yml
  test/bdd/fixtures/vault-server/.env
  test/bdd/fixtures/vault-server/docker-compose.yml
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/comparator/comparator_steps.go
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#635 fix: vault-server, comparator
  cmd/comparator-rest/docs/openapi.yaml
  pkg/client/comparator/models/scope.go
  pkg/client/vault/client.go
  pkg/restapi/comparator/operation/authz.go
  pkg/restapi/comparator/operation/compare.go
  pkg/restapi/comparator/operation/models/scope.go
  pkg/restapi/vault/client.go
  pkg/restapi/vault/client_test.go
  pkg/restapi/vault/operation/openapi.go
  pkg/restapi/vault/operation/operations_test.go
  test/bdd/fixtures/vault-server/docker-compose.yml
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/comparator/comparator_steps.go
  test/bdd/pkg/vault/vault_steps.go
Labels: bug, cla-signed, comparator, vault-server

#636 feat: confidential-storage-hub - /extract
  cmd/confidential-storage-hub/docs/openapi.yaml
  pkg/client/csh/client/operations/get_extract_parameters.go
  pkg/client/csh/client/operations/get_extract_responses.go
  pkg/client/csh/client/operations/operations_client.go
  pkg/client/csh/client/operations/post_extract_parameters.go
  pkg/client/csh/client/operations/post_extract_responses.go
  pkg/client/csh/client/operations/post_hubstore_profiles_profile_id_queries_responses.go
  pkg/restapi/csh/operation/openapi.go
  pkg/restapi/csh/operation/operations.go
  pkg/restapi/csh/operation/operations_test.go
  pkg/restapi/csh/operation/query_test.go
  test/bdd/features/confidential-storage-hub_e2e_api.feature
  test/bdd/pkg/chs/chs_steps.go
  test/bdd/pkg/chs/user.go
Labels: cla-signed, confidential-storage-hub, enhancement

#637 feat: Vault server - BDD decrypt.
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#634 test: add negative test for compare
  test/bdd/features/comparator_e2e_api.feature
  test/bdd/features/vault_server_e2e_api.feature
  test/bdd/pkg/comparator/comparator_steps.go
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#639 docs: additional hosts file entry for BDD tests
  docs/build.md
Labels: cla-signed

#638 refactor: Vault server - removes toDidURL usage
  .golangci.yml
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  go.mod
  go.sum
  pkg/auth/zcapld/service.go
  pkg/restapi/comparator/operation/authz.go
  pkg/restapi/comparator/operation/compare.go
  pkg/restapi/comparator/operation/operations.go
  pkg/restapi/csh/operation/operations.go
  pkg/restapi/csh/operation/operations_test.go
  pkg/restapi/csh/operation/query.go
  pkg/restapi/csh/operation/query_test.go
  pkg/restapi/vault/client.go
  pkg/restapi/vault/client_test.go
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/chs/chs_steps.go
  test/bdd/pkg/chs/user.go
Labels: cla-signed

#640 fix: bitstring set position
  pkg/doc/vc/status/csl/csl.go
  pkg/internal/common/utils/bitstring.go
  pkg/internal/common/utils/bitstring_test.go
  pkg/restapi/verifier/operation/operations.go
  test/bdd/features/vc_e2e_api.feature
  test/bdd/pkg/verifier/verifier_steps.go
Labels: cla-signed

#641 feat: Vault server - adds trustbloc did support
  cmd/common/storage.go
  cmd/comparator-rest/go.mod
  cmd/comparator-rest/go.sum
  cmd/comparator-rest/startcmd/start.go
  cmd/confidential-storage-hub/go.mod
  cmd/confidential-storage-hub/go.sum
  cmd/confidential-storage-hub/startcmd/start.go
  cmd/did-rest/go.mod
  cmd/did-rest/go.sum
  cmd/vault-server/go.mod
  cmd/vault-server/go.sum
  cmd/vault-server/startcmd/start.go
  cmd/vault-server/startcmd/start_test.go
  cmd/vc-rest/go.mod
  cmd/vc-rest/go.sum
  cmd/vc-rest/startcmd/start.go
  cmd/vc-rest/startcmd/start_test.go
  go.mod
  go.sum
  pkg/client/vault/reader_test.go
  pkg/doc/vc/profile/profile.go
  pkg/doc/vc/profile/profile_test.go
  pkg/doc/vc/profile/verifier/profile.go
  pkg/doc/vc/profile/verifier/profile_test.go
  pkg/doc/vc/status/csl/csl.go
  pkg/doc/vc/status/csl/csl_test.go
  pkg/internal/cryptosetup/cryptosetup.go
  pkg/restapi/comparator/controller_test.go
  pkg/restapi/comparator/operation/operations.go
  pkg/restapi/comparator/operation/operations_test.go
  pkg/restapi/csh/operation/query_test.go
  pkg/restapi/csh/operation/zcapld/zcapld_test.go
  pkg/restapi/governance/controller_test.go
  pkg/restapi/governance/operation/operations.go
  pkg/restapi/governance/operation/operations_test.go
  pkg/restapi/holder/controller_test.go
  pkg/restapi/holder/operation/operations.go
  pkg/restapi/holder/operation/operations_test.go
  pkg/restapi/issuer/controller_test.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/vault/client.go
  pkg/restapi/vault/client_test.go
  pkg/restapi/vault/operation/operations.go
  pkg/restapi/vault/operation/operations_test.go
  pkg/restapi/verifier/controller_test.go
  pkg/restapi/verifier/operation/operations.go
  pkg/restapi/verifier/operation/operations_test.go
  test/bdd/fixtures/vault-server/docker-compose.yml
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/chs/user.go
  test/bdd/pkg/comparator/comparator_steps.go
  test/bdd/pkg/vault/vault_steps.go
Labels: cla-signed

#642 feat: implement extract endpoint in comparator
  cmd/comparator-rest/docs/openapi.yaml
  pkg/client/comparator/client/operations/post_extract_parameters.go
  pkg/client/comparator/client/operations/post_extract_responses.go
  pkg/client/comparator/models/extract.go
  pkg/client/comparator/models/extract_resp.go
  pkg/restapi/comparator/operation/compare.go
  pkg/restapi/comparator/operation/extract.go
  pkg/restapi/comparator/operation/models/extract.go
  pkg/restapi/comparator/operation/models/extract_resp.go
  pkg/restapi/comparator/operation/openapi.go
  pkg/restapi/comparator/operation/operations.go
  pkg/restapi/comparator/operation/operations_test.go
  test/bdd/features/comparator_e2e_api.feature
  test/bdd/pkg/comparator/comparator_steps.go
Labels: cla-signed
